[package]
name = "hello"
version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
documentation.workspace = true

[[bin]]
name = "hello"
path = "src/main.rs"

[dependencies]
