name: Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust target for wasm
        run: |
          rustup target add wasm32-wasi

      - name: Build Wasm files
        run: |
          cd control
          cargo build --target wasm32-wasi --release
          cd ../function
          cargo build --target wasm32-wasi --release
          cd ../hello
          cargo build --target wasm32-wasi --release
          cd ../move
          cargo build --target wasm32-wasi --release
          cd ../server
          cargo build --target wasm32-wasi --release
          cd ../string
          cargo build --target wasm32-wasi --release
          cd ../struct
          cargo build --target wasm32-wasi --release
          cd ../wasi
          cargo build --target wasm32-wasi --release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: main
          release_name: rust-wasm-builds
          draft: false
          prerelease: false
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*/target/wasm32-wasi/release/*.wasm"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
